"""Added favorites table

Revision ID: cced73a04f93
Revises: 680e1e31d643
Create Date: 2022-10-13 06:15:54.683115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cced73a04f93'
down_revision = '680e1e31d643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anime_list_edition', table_name='anime_list')
    op.drop_table('anime_list')
    op.drop_index('ix_anime_episodes', table_name='anime')
    op.drop_index('ix_anime_id', table_name='anime')
    op.drop_index('ix_anime_ongoing', table_name='anime')
    op.drop_index('ix_anime_title', table_name='anime')
    op.drop_index('ix_anime_title_id', table_name='anime')
    op.drop_index('ix_anime_upcoming', table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('episodes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upcoming', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ongoing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anime_pkey')
    )
    op.create_index('ix_anime_upcoming', 'anime', ['upcoming'], unique=False)
    op.create_index('ix_anime_title_id', 'anime', ['title_id'], unique=False)
    op.create_index('ix_anime_title', 'anime', ['title'], unique=False)
    op.create_index('ix_anime_ongoing', 'anime', ['ongoing'], unique=False)
    op.create_index('ix_anime_id', 'anime', ['id'], unique=False)
    op.create_index('ix_anime_episodes', 'anime', ['episodes'], unique=False)
    op.create_table('anime_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edition', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isDubbed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anime_list_pkey')
    )
    op.create_index('ix_anime_list_edition', 'anime_list', ['edition'], unique=False)
    # ### end Alembic commands ###
