"""Added favorites table

Revision ID: eb1ae001d7f2
Revises: cced73a04f93
Create Date: 2022-10-13 06:19:20.557695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1ae001d7f2'
down_revision = 'cced73a04f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
